In [22]:
import numpy as np
import pandas as pd

In [23]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [24]:
df = pd.read_csv('covid_toy.csv')

In [25]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [26]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [27]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'],test_size=0.2)

In [29]:
X_train

    age  gender  fever   cough       city
97   20  Female  101.0    Mild  Bangalore
73   34    Male   98.0  Strong    Kolkata
37   55    Male  100.0    Mild    Kolkata
48   66    Male   99.0  Strong  Bangalore
87   47    Male  101.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
56   71    Male    NaN  Strong    Kolkata
4    65  Female  101.0    Mild     Mumbai
34   74    Male  102.0    Mild     Mumbai
95   12  Female  104.0    Mild  Bangalore
23   80  Female   98.0    Mild      Delhi

[80 rows x 5 columns]

In [30]:
#aam zindagi
#adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [31]:
#ordinalEncoder(categories=[['Mild','Strong']])
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
#also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [34]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse=False, handle_unknown='ignore')

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# FIX: use transform(), not fit_transform()
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'